const IDIOMS = [
  "The way to a sister's day is through a good lunch.",
  "Hunger is the best sauce.",
  "Variety is the spice of life.",
  "The proof of the pudding is in the eating.",
  "A watched pot never boils.",
  "Don't cry over spilled milk.",
  "Too many cooks spoil the broth.",
  "You are what you eat.",
  "An apple a day keeps the doctor away.",
  "The early bird catches the worm.",
  "Good things come to those who wait.",
  "Half a loaf is better than none.",
  "Don't put all your eggs in one basket.",
  "Out of the frying pan and into the fire.",
  "The pot calls the kettle black.",
  "A spoonful of honey catches more flies than vinegar.",
  "Eat to live, don't live to eat.",
  "Breakfast is gold, lunch is silver, dinner is quiet.",
  "A full belly makes a happy heart.",
  "Slow food, long life.",
  "The second bite tells the truth.",
  "Save room for what you love.",
  "A warm plate beats a perfect plan.",
  "Cook with patience, eat with joy.",
  "Little by little, the bowl fills.",
  "What you repeat becomes the meal.",
  "Fresh herbs forgive a plain pot.",
  "Salt late, taste often.",
  "The kitchen remembers who showed up.",
  "One good meal can steady a whole day.",
  "Share the bread, keep the peace.",
  "A simple supper is still a feast.",
  "Let the day ripen before you rush it.",
  "The best recipe is the one you actually cook.",
  "Taste before you judge.",
  "A calm table feeds more than hunger.",
  "Leave a little hunger for tomorrow.",
  "The oven teaches waiting.",
  "Chop slowly when the mind is loud.",
  "Water the day before you spice it.",
  "A sister's plate is never a test.",
  "Eat what loves you back.",
  "The clock can wait while the pan rests.",
  "Enough is a kind of plenty.",
  "A bright lunch makes a softer evening.",
  "Keep the good, leave the rest.",
  "The meal you finish is the meal that counts.",
  "Steam rises, and so does the mood.",
  "Put the phone down and pick up the fork.",
  "A bowl of soup is a small holiday.",
  "Color on the plate, color in the day.",
  "The first serving is for hunger. The second is a question.",
  "Trust the simmer.",
  "A clean glass of water is part of the meal.",
  "What is measured can be enjoyed.",
  "The day begins again at the next plate.",
  "Sweet after salt, rest after effort.",
  "A good knife and a good plan both need a steady hand.",
  "Don't season someone else's hunger.",
  "The table is a place, not a verdict.",
  "Warm bread, warm welcome.",
  "If it nourishes, it belongs.",
  "The shortest recipe is often the truest.",
  "Sit down to eat. Standing can wait.",
  "A peeled orange is a finished task.",
  "Let lunch be lunch and dinner be dinner.",
  "The body keeps the kinder promises.",
  "Stir until the worry thins.",
  "A market bag is a kind of hope.",
  "Choose the meal, then let it be chosen.",
  "The fast ends. The meal begins. Both are yours.",
  "Small plates, clear mind.",
  "What you prepare with care tastes like care.",
  "The last bite should still be pleasant.",
  "A day well fed is a day half solved.",
  "Keep one meal easy and one meal interesting.",
  "The pantry is a quiet friend.",
  "Eat the rainbow, skip the lecture.",
  "A timer in the kitchen beats a worry in the head.",
  "The best leftovers are yesterday's good idea.",
  "Set the table even when you eat alone.",
  "A ripe tomato needs no speech.",
  "Chew the day slowly.",
  "The spoon knows the way to the bottom of the pot.",
  "Make it tasty. Make it enough.",
  "A sister who eats is a sister who stays.",
  "New day, new plate, same love.",
  "The crust is where the patience went.",
  "Cool the soup before you blame the cook.",
  "A pinch of salt and a pinch of courage.",
  "Feed the hour you are actually in.",
  "The menu is long. Your day is one plate at a time.",
  "What is shared gets larger.",
  "A walk after dinner is the second dessert.",
  "Keep the bones of the day and the meat of the joy.",
  "The fridge light is not a mood.",
  "Plan the meal, then live the meal.",
  "A gentle breakfast can carry a loud afternoon.",
  "The pot is big enough for two.",
  "Taste with attention and the food answers.",
  "Today's lunch is tomorrow's strength.",
  "A lid on the pot keeps the heat and the peace.",
  "Choose nourishment the way you choose friends.",
  "The evening meal closes the book kindly.",
  "A full glass and an empty grudge.",
  "Let the colors lead and the numbers follow.",
  "The kitchen clock is kinder than the one on the wall.",
  "One honest meal is a whole victory.",
  "Butter on the bread, mercy on the day.",
  "The recipe can bend. The care should not.",
  "A quiet bite is still a celebration.",
  "Bring an appetite and leave the scorecard.",
  "The day tastes better when you sit down for it.",
  "Save the best bite, then give it to yourself.",
  "A stew gets better when nobody rushes it.",
  "The plate in front of you is the one that matters.",
  "Eat like someone who intends to stay well.",
  "A good lunch is a promise kept.",
  "The spice is optional. The kindness is not.",
  "When the fast opens, let the first bite be gentle.",
  "Two meals, one day, and a little room to breathe.",
  "The table you return to is the table that knows you.",
  "Make today delicious enough to remember.",
  "A peeled clove of garlic is already progress.",
  "The hungrier the hour, the simpler the win.",
  "Keep supper kind.",
  "What you eat at noon still whispers at night.",
  "A fresh start can be as small as a clean plate.",
  "The meal is ready when you are, and not a minute meaner.",
  "Love shows up as groceries sometimes.",
  "Take the portion that lets you stay yourself.",
  "A sunny egg can rescue a gray morning.",
  "The best diet is the one you can sit down to happily.",
  "Stir the pot, not the worry.",
  "Today's menu is a kindness you decided on.",
  "A sister's day deserves a real meal.",
  "From market to mouth, keep it honest.",
  "The second meal of the day is allowed to be joyful.",
  "Close the kitchen when the day is full.",
  "A bowl, a chair, a breath. That is dining.",
  "Let the numbers serve the meal, never the other way around.",
  "Another day, another chance to eat well.",
  "The heart stays softer when the plate is warm.",
  "Pick the food, then put the choosing down.",
  "A finished meal is a finished kindness.",
  "May the next bite be the one you wanted.",
];

export function idiomFor(dateKey) {
  let hash = 2166136261;
  for (let index = 0; index < dateKey.length; index += 1) {
    hash ^= dateKey.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return IDIOMS[(hash >>> 0) % IDIOMS.length];
}
